import { User, Shop, Visit, Streak, Voucher, RewardTier } from '../types';
import { dateNDaysAgo, toDateString, addDays } from '../utils/dates';
import { generateVoucherCode } from '../utils/formatters';

const today = toDateString(new Date());

function tiers(shopId: string): RewardTier[] {
  return [
    { id: `${shopId}_v5`, shopId, type: 'visit_count', threshold: 5, discountPercent: 10, label: 'Regular', description: '10% off your meal', emoji: '🥉' },
    { id: `${shopId}_v10`, shopId, type: 'visit_count', threshold: 10, discountPercent: 20, label: 'Loyal Fan', description: '20% off your meal', emoji: '🥈' },
    { id: `${shopId}_v20`, shopId, type: 'visit_count', threshold: 20, discountPercent: 30, label: 'VIP', description: '30% off your meal', emoji: '🥇' },
    { id: `${shopId}_v50`, shopId, type: 'visit_count', threshold: 50, discountPercent: 50, label: 'Legend', description: '50% off your meal', emoji: '👑' },
    { id: `${shopId}_s3`, shopId, type: 'streak_days', threshold: 3, discountPercent: 5, label: '3-Day Streak', description: '5% off next visit', emoji: '🔥' },
    { id: `${shopId}_s7`, shopId, type: 'streak_days', threshold: 7, discountPercent: 15, label: '7-Day Streak', description: '15% off next visit', emoji: '🔥' },
    { id: `${shopId}_s14`, shopId, type: 'streak_days', threshold: 14, discountPercent: 25, label: '14-Day Streak', description: '25% off next visit', emoji: '🔥' },
    { id: `${shopId}_s30`, shopId, type: 'streak_days', threshold: 30, discountPercent: 40, label: '30-Day Streak', description: '40% off — legendary!', emoji: '💎' },
  ];
}

export const MOCK_SHOPS: Shop[] = [
  {
    id: 'shop_nonna',
    name: "Nonna's Kitchen",
    ownerId: 'user_nadia',
    category: 'bistro',
    emoji: '🍝',
    description: 'Authentic Italian comfort food made with love. Fresh pasta daily.',
    address: '42 Olive Lane, Downtown',
    rewardTiers: tiers('shop_nonna'),
    streakWindowDays: 3,
    createdAt: '2025-01-15',
  },
  {
    id: 'shop_ramen',
    name: 'Ramen Bar 88',
    ownerId: 'user_owner2',
    category: 'ramen',
    emoji: '🍜',
    description: 'Rich tonkotsu broth, handmade noodles. Open late.',
    address: '88 Noodle St, Eastside',
    rewardTiers: tiers('shop_ramen'),
    streakWindowDays: 2,
    createdAt: '2025-02-01',
  },
  {
    id: 'shop_blueroast',
    name: 'Blue Roast Coffee',
    ownerId: 'user_owner3',
    category: 'coffee',
    emoji: '☕',
    description: 'Single-origin pour-overs and seasonal espresso blends.',
    address: '7 Bean Ave, Midtown',
    rewardTiers: tiers('shop_blueroast'),
    streakWindowDays: 3,
    createdAt: '2025-01-20',
  },
  {
    id: 'shop_masa',
    name: 'Masa Taqueria',
    ownerId: 'user_owner4',
    category: 'mexican',
    emoji: '🌮',
    description: 'Street-style tacos, fresh salsas, and house-made horchata.',
    address: '15 Fiesta Blvd, Westside',
    rewardTiers: tiers('shop_masa'),
    streakWindowDays: 4,
    createdAt: '2025-03-01',
  },
  {
    id: 'shop_sweetrise',
    name: 'Sweet Rise Bakery',
    ownerId: 'user_owner5',
    category: 'bakery',
    emoji: '🥐',
    description: 'Artisan pastries, sourdough bread, and weekend brunch specials.',
    address: '3 Flour Ct, Uptown',
    rewardTiers: tiers('shop_sweetrise'),
    streakWindowDays: 3,
    createdAt: '2025-02-10',
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'user_maya',
    name: 'Maya',
    email: 'maya@eatstreak.app',
    role: 'customer',
    joinedAt: '2025-03-01',
  },
  {
    id: 'user_nadia',
    name: 'Nadia Halvorsen',
    email: 'nadia@nonnas.kitchen',
    role: 'owner',
    joinedAt: '2025-01-15',
  },
];

function generateVisits(userId: string, shopId: string, streakDays: number): Visit[] {
  const visits: Visit[] = [];
  for (let i = streakDays - 1; i >= 0; i--) {
    visits.push({
      id: `visit_${shopId}_${i}`,
      userId,
      shopId,
      timestamp: dateNDaysAgo(i) + 'T12:00:00Z',
    });
  }
  return visits;
}

export const MOCK_VISITS: Visit[] = [
  ...generateVisits('user_maya', 'shop_nonna', 12),
  ...generateVisits('user_maya', 'shop_ramen', 7),
  ...generateVisits('user_maya', 'shop_blueroast', 21),
  {
    id: 'visit_masa_1',
    userId: 'user_maya',
    shopId: 'shop_masa',
    timestamp: dateNDaysAgo(5) + 'T12:00:00Z',
  },
  {
    id: 'visit_masa_2',
    userId: 'user_maya',
    shopId: 'shop_masa',
    timestamp: dateNDaysAgo(4) + 'T12:00:00Z',
  },
];

export const MOCK_STREAKS: Streak[] = [
  {
    id: 'streak_nonna',
    userId: 'user_maya',
    shopId: 'shop_nonna',
    currentStreakDays: 12,
    longestStreakDays: 12,
    totalVisits: 12,
    lastVisitDate: today,
    streakStartDate: dateNDaysAgo(11),
    isStreakAlive: true,
  },
  {
    id: 'streak_ramen',
    userId: 'user_maya',
    shopId: 'shop_ramen',
    currentStreakDays: 7,
    longestStreakDays: 7,
    totalVisits: 7,
    lastVisitDate: today,
    streakStartDate: dateNDaysAgo(6),
    isStreakAlive: true,
  },
  {
    id: 'streak_blueroast',
    userId: 'user_maya',
    shopId: 'shop_blueroast',
    currentStreakDays: 21,
    longestStreakDays: 21,
    totalVisits: 21,
    lastVisitDate: today,
    streakStartDate: dateNDaysAgo(20),
    isStreakAlive: true,
  },
  {
    id: 'streak_masa',
    userId: 'user_maya',
    shopId: 'shop_masa',
    currentStreakDays: 2,
    longestStreakDays: 2,
    totalVisits: 2,
    lastVisitDate: dateNDaysAgo(4),
    streakStartDate: dateNDaysAgo(5),
    isStreakAlive: false,
  },
];

export const MOCK_VOUCHERS: Voucher[] = [
  {
    id: 'voucher_nonna_v5',
    userId: 'user_maya',
    shopId: 'shop_nonna',
    shopName: "Nonna's Kitchen",
    shopEmoji: '🍝',
    tierId: 'shop_nonna_v5',
    type: 'visit_count',
    discountPercent: 10,
    tierLabel: 'Regular',
    earnedAt: dateNDaysAgo(7) + 'T12:00:00Z',
    expiresAt: addDays(today, 23) + 'T23:59:59Z',
    isRedeemed: false,
    redeemedAt: null,
    code: generateVoucherCode(),
  },
  {
    id: 'voucher_nonna_v10',
    userId: 'user_maya',
    shopId: 'shop_nonna',
    shopName: "Nonna's Kitchen",
    shopEmoji: '🍝',
    tierId: 'shop_nonna_v10',
    type: 'visit_count',
    discountPercent: 20,
    tierLabel: 'Loyal Fan',
    earnedAt: dateNDaysAgo(2) + 'T12:00:00Z',
    expiresAt: addDays(today, 28) + 'T23:59:59Z',
    isRedeemed: false,
    redeemedAt: null,
    code: generateVoucherCode(),
  },
  {
    id: 'voucher_ramen_s7',
    userId: 'user_maya',
    shopId: 'shop_ramen',
    shopName: 'Ramen Bar 88',
    shopEmoji: '🍜',
    tierId: 'shop_ramen_s7',
    type: 'streak_days',
    discountPercent: 15,
    tierLabel: '7-Day Streak',
    earnedAt: today + 'T12:00:00Z',
    expiresAt: addDays(today, 30) + 'T23:59:59Z',
    isRedeemed: false,
    redeemedAt: null,
    code: generateVoucherCode(),
  },
  {
    id: 'voucher_blueroast_v10',
    userId: 'user_maya',
    shopId: 'shop_blueroast',
    shopName: 'Blue Roast Coffee',
    shopEmoji: '☕',
    tierId: 'shop_blueroast_v10',
    type: 'visit_count',
    discountPercent: 20,
    tierLabel: 'Loyal Fan',
    earnedAt: dateNDaysAgo(11) + 'T12:00:00Z',
    expiresAt: addDays(today, 19) + 'T23:59:59Z',
    isRedeemed: true,
    redeemedAt: dateNDaysAgo(5) + 'T14:00:00Z',
    code: generateVoucherCode(),
  },
  {
    id: 'voucher_blueroast_v20',
    userId: 'user_maya',
    shopId: 'shop_blueroast',
    shopName: 'Blue Roast Coffee',
    shopEmoji: '☕',
    tierId: 'shop_blueroast_v20',
    type: 'visit_count',
    discountPercent: 30,
    tierLabel: 'VIP',
    earnedAt: dateNDaysAgo(1) + 'T12:00:00Z',
    expiresAt: addDays(today, 29) + 'T23:59:59Z',
    isRedeemed: false,
    redeemedAt: null,
    code: generateVoucherCode(),
  },
  {
    id: 'voucher_blueroast_s14',
    userId: 'user_maya',
    shopId: 'shop_blueroast',
    shopName: 'Blue Roast Coffee',
    shopEmoji: '☕',
    tierId: 'shop_blueroast_s14',
    type: 'streak_days',
    discountPercent: 25,
    tierLabel: '14-Day Streak',
    earnedAt: dateNDaysAgo(7) + 'T12:00:00Z',
    expiresAt: addDays(today, 23) + 'T23:59:59Z',
    isRedeemed: false,
    redeemedAt: null,
    code: generateVoucherCode(),
  },
];
