#!/usr/bin/env python3
"""Generate real QR images for the end-to-end scan test, and prove they decode.

Why generate rather than download a menu QR from the web: this suite is meant to
be run constantly, and a fixture that depends on some restaurant's CDN staying up
fails for reasons that have nothing to do with EatStreak. The payloads below are
copied from the shapes real codes actually use — a Malaysian DuitNow/UPI string,
a Google Maps place link, a bare menu URL — so the app sees the same bytes it
would off a laminated table card, without the network in the way.

The QR is generated by OpenCV and then decoded again by OpenCV's *detector*,
which is a separate code path from the encoder and knows nothing about EatStreak.
That round trip is what stands in for the camera: if the detector reads back the
exact string we encoded, the image is genuinely scannable, and the only thing the
simulator is missing is the lens.

Usage:
    python3 tool/e2e/qr_fixtures.py --out <dir> [--link-domain <host>] [--shop <id>]

Writes <dir>/*.png plus <dir>/manifest.json, and exits non-zero if any fixture
fails to decode back to its source string.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import cv2
import numpy as np

# Kept in step with Env.linkDomain in mobile/lib/core/config/env.dart, which
# derives it from the Firebase project id.
DEFAULT_LINK_DOMAIN = "eatstreak-prod.web.app"

# A shop from mobile/lib/data/seed/mock_data.dart, so a demo-mode build resolves
# it to a real shop instead of the not-found branch.
DEFAULT_SHOP = "shop_ramen"


def fixtures(link_domain: str, shop: str) -> list[dict]:
    """Every payload the scanner has to survive, and where each should land.

    `expect` is the branch scanner_screen._route() should take — the thing to
    check each screenshot against. Not the pixels, which change with every
    design tweak.

    Two things the demo-mode build cannot show you, so do not read them into a
    green run:

    * **Day codes are not validated.** `DemoRepository.checkIn` ignores the
      token by design — there is no server to mint one against. Whether a
      codeless or stale code is refused is settled server-side and is covered by
      `functions/src/checkInToken.test.ts`, not here.
    * **Fixtures share one device.** They run in order against the same seeded
      data, so the first EatStreak code checks in at the shop and every later
      code for that shop lands on `already_visited_today`. That is correct
      behaviour, and it is why the second fixture below uses a different shop.
    """
    token = f"demo_{shop}_TESTTOKEN"
    return [
        # ---- EatStreak codes: these must check in -------------------------
        {
            "name": "eatstreak_universal_link",
            "payload": f"https://{link_domain}/c/{shop}?t={token}",
            "expect": "check_in",
            "why": "The canonical printed code: buildCheckInLink() with the day's token.",
        },
        {
            "name": "eatstreak_same_shop_twice",
            "payload": f"https://{link_domain}/c/{shop}?t={token}",
            "expect": "already_visited_today (toast, stays on scanner)",
            "why": (
                "The same code scanned again minutes later — a customer double-taps, "
                "or staff rescan. Must not log a second visit or inflate the streak. "
                "Depends on the fixture above having run first."
            ),
        },
        {
            "name": "eatstreak_link_no_token",
            "payload": f"https://{link_domain}/c/shop_blueroast",
            "expect": "check_in (demo mode ignores the day code — see docstring)",
            "why": (
                "A shop link with the day code stripped off. Against the live backend "
                "this is refused as code_invalid; demo mode has no server to check it, "
                "so all this fixture proves is that a codeless link still routes and "
                "does not crash. A different shop, so it is not masked by the repeat above."
            ),
        },
        {
            "name": "eatstreak_legacy_scheme",
            "payload": f"eatstreak://check-in/{shop}?t={token}",
            "expect": "check_in",
            "why": "Codes printed before the switch to universal links still work.",
        },
        {
            "name": "eatstreak_unknown_shop",
            "payload": f"https://{link_domain}/c/shop_does_not_exist?t={token}",
            "expect": "shop_not_found",
            "why": "A real EatStreak code for a shop that is gone.",
        },
        # ---- Real-world codes a customer will point the app at ------------
        {
            "name": "menu_url",
            "payload": "https://menu.warungpakcik.com.my/table/12",
            "expect": "external_qr",
            "why": "The ordinary table-tent menu QR. The single most likely wrong scan.",
        },
        {
            "name": "menu_google_maps",
            "payload": "https://www.google.com/maps/place/Restoran+Nasi+Kandar+Pelita/@3.1578,101.7118,17z",
            "expect": "external_qr",
            "why": "Shopfront window sticker. Should prefill the suggestion form with the name.",
        },
        {
            "name": "payment_duitnow_upi",
            "payload": "upi://pay?pa=warung@maybank&pn=Warung%20Pak%20Cik&cu=MYR",
            "expect": "external_qr",
            "why": "The payment QR sitting next to the till — scanned by mistake constantly.",
        },
        {
            "name": "wifi_credentials",
            "payload": "WIFI:S:WarungPakCik_Guest;T:WPA;P:makanlah123;;",
            "expect": "external_qr",
            "why": "Not a URL at all. Must not crash or be mistaken for a shop link.",
        },
        {
            "name": "empty_ish_text",
            "payload": "   ",
            "expect": "external_qr",
            "why": "Whitespace-only payload — the degenerate case that tends to throw.",
        },
    ]


def encode(payload: str, path: pathlib.Path) -> None:
    """Write `payload` as a real QR PNG, upscaled so a detector can lock on."""
    encoder = cv2.QRCodeEncoder_create()
    img = encoder.encode(payload)
    # Nearest-neighbour so module edges stay hard; a blurred QR is a flaky test.
    big = cv2.resize(img, None, fx=8, fy=8, interpolation=cv2.INTER_NEAREST)
    # A quiet zone is part of the spec — without it detection rate drops.
    framed = cv2.copyMakeBorder(big, 40, 40, 40, 40, cv2.BORDER_CONSTANT, value=255)
    cv2.imwrite(str(path), framed)


def decode(path: pathlib.Path) -> str | None:
    """Read a QR back with the detector — the encoder is not involved."""
    img = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
    if img is None:
        return None
    ok, decoded, _, _ = cv2.QRCodeDetector().detectAndDecodeMulti(img)
    if not ok or not decoded:
        return None
    return decoded[0]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument("--link-domain", default=DEFAULT_LINK_DOMAIN)
    ap.add_argument("--shop", default=DEFAULT_SHOP)
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    entries = fixtures(args.link_domain, args.shop)

    failures = 0
    for f in entries:
        png = args.out / f"{f['name']}.png"

        # A QR cannot encode an empty string; such a payload can still reach
        # _route() from a damaged scan, so it stays in the manifest for the
        # driver and is simply not rendered.
        if not f["payload"].strip():
            f["png"] = None
            f["roundtrip"] = "skipped (not encodable as a QR)"
            print(f"  --  {f['name']}: no image, payload is whitespace")
            continue

        encode(f["payload"], png)
        got = decode(png)
        f["png"] = str(png)

        if got == f["payload"]:
            f["roundtrip"] = "ok"
            print(f"  ok  {f['name']}: {len(f['payload'])} chars survived encode->decode")
        else:
            f["roundtrip"] = "FAILED"
            failures += 1
            print(f"FAIL  {f['name']}: encoded {f['payload']!r}, decoded {got!r}")

    manifest = args.out / "manifest.json"
    manifest.write_text(json.dumps(entries, indent=2))
    print(f"\n{len(entries) - failures}/{len(entries)} fixtures verified -> {manifest}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
