#!/usr/bin/env python3
"""Generate real QR images for the end-to-end scan test, and prove they decode.

Why generate rather than download a menu QR from the web: this suite is meant to
be run constantly, and a fixture that depends on some restaurant's CDN staying up
fails for reasons that have nothing to do with EatStreak. The payloads below are
copied from the shapes real codes actually use — a Malaysian DuitNow/UPI string,
a Google Maps place link, a bare menu URL — so the app sees the same bytes it
would off a laminated table card, without the network in the way.

The QR is generated by OpenCV and then decoded again by OpenCV's *detector*,
which is a separate code path from the encoder and knows nothing about EatStreak.
That round trip is what stands in for the camera: if the detector reads back the
exact string we encoded, the image is genuinely scannable, and the only thing the
simulator is missing is the lens.

Usage:
    python3 tool/e2e/qr_fixtures.py --out <dir> [--link-domain <host>] [--shop <id>]
                                    [--project <firebase-project-id>]

Writes <dir>/*.png plus <dir>/manifest.json, and exits non-zero if any fixture
fails to decode back to its source string.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import cv2
import numpy as np

# Kept in step with Env.linkDomain in mobile/lib/core/config/env.dart, which
# derives it from the Firebase project id.
DEFAULT_LINK_DOMAIN = "eatstreak-prod.web.app"

# A shop from mobile/lib/data/seed/mock_data.dart, so a demo-mode build resolves
# it to a real shop instead of the not-found branch.
DEFAULT_SHOP = "shop_ramen"

# Firebase Hosting serves each site on <project>.web.app *and*
# <project>.firebaseapp.com, and qr_codec.dart's _checkInHosts accepts both.
# Kept in step with FIREBASE_PROJECT_ID in tool/e2e/env.e2e.json — the app only
# resolves the second host when the build knows its project id.
DEFAULT_PROJECT = "eatstreak-prod"


def fixtures(link_domain: str, shop: str, project: str) -> list[dict]:
    """Every payload the scanner has to survive, and where each should land.

    `expect` is the branch scanner_screen._route() should take — the thing to
    check each screenshot against. Not the pixels, which change with every
    design tweak.

    Two things the demo-mode build cannot show you, so do not read them into a
    green run:

    * **Day codes are not validated.** `DemoRepository.checkIn` ignores the
      token by design — there is no server to mint one against. Whether a
      codeless or stale code is refused is settled server-side and is covered by
      `functions/src/checkInToken.test.ts`, not here.
    * **Fixtures share one device.** They run in order against the same seeded
      data, so the first EatStreak code checks in at the shop and every later
      code for that shop lands on `already_visited_today`. That is correct
      behaviour, and it is why the second fixture below uses a different shop.
    """
    token = f"demo_{shop}_TESTTOKEN"
    return [
        # ---- EatStreak codes: these must check in -------------------------
        {
            "name": "eatstreak_universal_link",
            "payload": f"https://{link_domain}/c/{shop}?t={token}",
            "expect": "check_in",
            "why": "The canonical printed code: buildCheckInLink() with the day's token.",
        },
        {
            "name": "eatstreak_same_shop_twice",
            "payload": f"https://{link_domain}/c/{shop}?t={token}",
            "expect": "already_visited_today (toast, stays on scanner)",
            "why": (
                "The same code scanned again minutes later — a customer double-taps, "
                "or staff rescan. Must not log a second visit or inflate the streak. "
                "Depends on the fixture above having run first."
            ),
        },
        {
            "name": "eatstreak_link_no_token",
            "payload": f"https://{link_domain}/c/shop_blueroast",
            "expect": "check_in (demo mode ignores the day code — see docstring)",
            "why": (
                "A shop link with the day code stripped off. Against the live backend "
                "this is refused as code_invalid; demo mode has no server to check it, "
                "so all this fixture proves is that a codeless link still routes and "
                "does not crash. A different shop, so it is not masked by the repeat above."
            ),
        },
        {
            "name": "eatstreak_legacy_scheme",
            "payload": f"eatstreak://check-in/{shop}?t={token}",
            "expect": "check_in",
            "why": "Codes printed before the switch to universal links still work.",
        },
        {
            "name": "eatstreak_unknown_shop",
            "payload": f"https://{link_domain}/c/shop_does_not_exist?t={token}",
            "expect": "shop_not_found",
            "why": "A real EatStreak code for a shop that is gone.",
        },
        {
            "name": "eatstreak_firebaseapp_host",
            "payload": f"https://{project}.firebaseapp.com/c/shop_masa?t=demo_shop_masa_TESTTOKEN",
            "expect": "check_in",
            "why": (
                "Firebase Hosting serves every site on BOTH <project>.web.app and "
                "<project>.firebaseapp.com, and a code printed from either host is a "
                "real code. _checkInHosts accepts both; only one of them had ever "
                "been exercised here. A different shop, so it is a genuine check-in "
                "rather than a repeat."
            ),
        },
        {
            "name": "eatstreak_uppercase_host",
            "payload": f"https://{link_domain.upper()}/c/shop_nonna?t=demo_shop_nonna_TESTTOKEN",
            "expect": "check_in",
            "why": (
                "Hosts are case-insensitive and some QR generators upper-case the "
                "whole payload to shrink the symbol. Uri normalises the host; this "
                "pins that we rely on it."
            ),
        },
        {
            "name": "eatstreak_host_suffix_spoof",
            "payload": f"https://{link_domain}.evil.example/c/{shop}?t={token}",
            "expect": "external_qr",
            "why": (
                "A hostile code whose host merely *starts* with ours. If the host "
                "test were a prefix or substring match instead of an equality one, "
                "this would check the customer in at somebody else's say-so — and "
                "the check-in link is the one payload in this app that causes a "
                "write. It must land on the external branch, not the check-in one."
            ),
        },
        # ---- our own voucher code, pointed at the wrong scanner ------------
        {
            "name": "eatstreak_own_voucher",
            "payload": "EATSTREAK:V1:VOUCHER:EAT-ABC123",
            "expect": "external_qr, and NO name prefilled in the suggestion form",
            "why": (
                "A customer scanning their own voucher with the customer scanner. "
                "It is the only other code in this app, so this is a normal "
                "mistake. Before _isMachinePayload listed the voucher prefix, the "
                "app offered 'EATSTREAK:V1:VOUCHER:EAT-ABC123' as the name of a "
                "restaurant to add — the wifi bug in our own payload."
            ),
        },
        # ---- Real-world codes a customer will point the app at ------------
        {
            "name": "menu_url",
            "payload": "https://menu.warungpakcik.com.my/table/12",
            "expect": "external_qr",
            "why": "The ordinary table-tent menu QR. The single most likely wrong scan.",
        },
        {
            "name": "menu_google_maps",
            "payload": "https://www.google.com/maps/place/Restoran+Nasi+Kandar+Pelita/@3.1578,101.7118,17z",
            "expect": "external_qr",
            "why": "Shopfront window sticker. Should prefill the suggestion form with the name.",
        },
        {
            "name": "payment_duitnow_upi",
            "payload": "upi://pay?pa=warung@maybank&pn=Warung%20Pak%20Cik&cu=MYR",
            "expect": "external_qr",
            "why": "The payment QR sitting next to the till — scanned by mistake constantly.",
        },
        {
            "name": "wifi_credentials",
            "payload": "WIFI:S:WarungPakCik_Guest;T:WPA;P:makanlah123;;",
            "expect": "external_qr",
            "why": "Not a URL at all. Must not crash or be mistaken for a shop link.",
        },
        {
            "name": "vcard_contact",
            "payload": (
                "BEGIN:VCARD\nVERSION:3.0\nFN:Warung Pak Cik\n"
                "TEL:+60123456789\nEND:VCARD"
            ),
            "expect": "external_qr, and NO name prefilled",
            "why": (
                "The owner's contact card on the shopfront. It *does* contain the "
                "shop name, but as one field of a structured payload — offering the "
                "whole vCard as a name is what the 80-character rule used to do."
            ),
        },
        {
            "name": "otpauth_seed",
            "payload": "otpauth://totp/Warung:staff?secret=JBSWY3DPEHPK3PXP&issuer=Warung",
            "expect": "external_qr, and NO name prefilled",
            "why": (
                "A 2FA enrolment code left on a back-office noticeboard. The payload "
                "is a shared secret; it must never be copied into a shopSuggestions "
                "document, which is exactly what prefilling it as a name would do."
            ),
        },
        {
            "name": "tel_number",
            "payload": "tel:+60123456789",
            "expect": "external_qr, and NO name prefilled",
            "why": "A takeaway flyer's call-us code. A phone number is not a name.",
        },
        {
            "name": "plain_shop_name",
            "payload": "Warung Pak Cik",
            "expect": "external_qr, name prefilled as 'Warung Pak Cik'",
            "why": (
                "The path that is supposed to work: a hand-made code with nothing "
                "but the shop's name in it. Every fixture above proves we reject a "
                "name; this one proves we still accept one."
            ),
        },
        {
            "name": "long_tracking_url",
            "payload": (
                "https://order.foodpanda.my/restaurant/x9k2/warung-pak-cik"
                "?utm_source=qr&utm_medium=table&utm_campaign=lunch2026"
                "&utm_content=tent-card-a&session=7f3c9b1e2d4a"
            ),
            "expect": "external_qr, name prefilled from the host",
            "why": (
                "A delivery-aggregator code with a long query string. Length is what "
                "pushes a QR into a denser symbol, so it is also the fixture most "
                "likely to stop decoding if the encoder settings drift."
            ),
        },
        {
            "name": "empty_ish_text",
            "payload": "   ",
            "expect": "external_qr",
            "why": "Whitespace-only payload — the degenerate case that tends to throw.",
        },
    ]


def encode(payload: str, path: pathlib.Path) -> None:
    """Write `payload` as a real QR PNG, upscaled so a detector can lock on."""
    encoder = cv2.QRCodeEncoder_create()
    img = encoder.encode(payload)
    # Nearest-neighbour so module edges stay hard; a blurred QR is a flaky test.
    big = cv2.resize(img, None, fx=8, fy=8, interpolation=cv2.INTER_NEAREST)
    # A quiet zone is part of the spec — without it detection rate drops.
    framed = cv2.copyMakeBorder(big, 40, 40, 40, 40, cv2.BORDER_CONSTANT, value=255)
    cv2.imwrite(str(path), framed)


def decode(path: pathlib.Path) -> str | None:
    """Read a QR back with the detector — the encoder is not involved."""
    img = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
    if img is None:
        return None
    ok, decoded, _, _ = cv2.QRCodeDetector().detectAndDecodeMulti(img)
    if not ok or not decoded:
        return None
    return decoded[0]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument("--link-domain", default=DEFAULT_LINK_DOMAIN)
    ap.add_argument("--shop", default=DEFAULT_SHOP)
    ap.add_argument("--project", default=DEFAULT_PROJECT)
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    entries = fixtures(args.link_domain, args.shop, args.project)

    failures = 0
    for f in entries:
        png = args.out / f"{f['name']}.png"

        # A QR cannot encode an empty string; such a payload can still reach
        # _route() from a damaged scan, so it stays in the manifest for the
        # driver and is simply not rendered.
        if not f["payload"].strip():
            f["png"] = None
            f["roundtrip"] = "skipped (not encodable as a QR)"
            print(f"  --  {f['name']}: no image, payload is whitespace")
            continue

        encode(f["payload"], png)
        got = decode(png)
        f["png"] = str(png)

        if got == f["payload"]:
            f["roundtrip"] = "ok"
            print(f"  ok  {f['name']}: {len(f['payload'])} chars survived encode->decode")
        else:
            f["roundtrip"] = "FAILED"
            failures += 1
            print(f"FAIL  {f['name']}: encoded {f['payload']!r}, decoded {got!r}")

    manifest = args.out / "manifest.json"
    manifest.write_text(json.dumps(entries, indent=2))
    print(f"\n{len(entries) - failures}/{len(entries)} fixtures verified -> {manifest}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
